### PR TITLE
Multi comp cell file added with tests

### LINKED ISSUE #13: Add test hoc/python script to load full cell from example 1 & save results to file & add OMV test
Along the lines of https://github.com/OpenSourceBrain/BlueBrainProjectShowcase/blob/master/NMC/NEURON/Test_L1.hoc
Again best in https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/tree/master/NEURON/test.

### PR DESCRIPTION
**Pull request by shayanshafquat**
I have added NEURON tests for the multi compartmental nml file on the membrane potential of the soma section. The shape of soma(0.25), apical(0.6), tuft(0.5) is similar both in shape and magnitude.

Shortcomings:
1. Tried adding netpyne tests too but its failing because it observes an extra spike.
2. Vshift for [nat (iseg)](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/7da08a234aadca85e8e104c9db59cc8944583e29/NeuroML2/pyr.cell.nml#L269) is set in nml file by adding vshift+vshift2 i.e. 10mv + -10.612583mV. Is there a way to directly pass the variable vShift2 from py file.

### CODE REVIEW

**Comment by pgleeson** [comment]
@shayan823 Looks good, but probably best not to commit the cellCheck/nctools here. You're using the newer version from pyneuroml anyway, correct? Also, don;t change any of the other hoc scripts in the original code, change it in your test files if necessary.

**Comment by shayanshafquat** [comment]
Yeah, now I am using the pyneuroml version of cellCheck/nCtools. Have removed them and reverted back the changes I made to the original hoc files. I think we can merge them now. @pgleeson

**Comment by pgleeson** [comment]
@shayan823 I notice there are no segments added to the group dendrite_group. Easiest to add the other defined dend seg groups to this, like apical. 

Also NEURON/reduced_geometry_20com.hoc and  NEURON/reduced_model.hoc are changed in this PR. Only trivial changes, but it would still be good to keep the original files as unaltered as possible, so others don't have to check through our commits to see there are no meaningful changes.

**Comment by shayanshafquat** [comment]
@pgleeson Okay. I will add the segments apical and tuft to the dendrite group. Are the segments hillock, iseg and axon also supposed to be added to it? 

I wanted to ask this today, but how does adding this to soma, axon, dendrite group will help us in visualization as mentioned [here](https://docs.neuroml.org/Userdocs/Conventions.html#neuron-segments).

Have reverted the hoc files to original version as it was.

**Comment by pgleeson** [comment]
Sorry @shayan823 thought I replied already...

See https://www.opensourcebrain.org/projects/bahletal2012_reducedl5pyrcell/models?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FBahlEtAl2012_ReducedL5PyrCell%252Fmaster%252FNeuroML2%252Fpyr_multi_comp.net.nml 

All of the cell should be either blue/orange/green when the "Highlight cell regions is selected". 
hillock, iseg and axon should all be in axon_group

Screenshot 2022-08-31 at 10 20 59

**Comment by shayanshafquat** [comment]
Closing this issue as the changes proposed have been already merged into the master branch.

**Pull request closed without merging**
